version: '3'

services:

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile.prod
    container_name: app
    #entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: web
    networks: 
      - node-network  
    volumes: 
        - ./nginx:/usr/local/etc/nginx
    ports: 
      - "8080:80"
       
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge  